Styling
tomasesquivelgc/React-Redux-bookstore pull request #5
Opened 2023-06-25 03:26 UTC by tomasesquivelgc

## In this branch:

 - CSS is added to the project.

_Note: some differences from the original template may be present due to time constraints. I ask of thee to have mercy upon my soul_

2023-06-25 03:53 UTC, 1GORDON requested changes
##
## Hi @tomasesquivelgc ✋

Good job so far!

## Highlights!
- Basic styling well implemented ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-25 03:53 UTC, 1GORDON commented on src/styles/Book.css
> +  font-weight: bold;
Great job @tomasesquivelgc  🤝

- [ ] As stated in the project requirements, kindly ensure there is no repeating of the same rule. Instead, create a single class to represent this rule and reuse this class where necessary. For example make sure the following classes are not repeated. `font-family: Montserrat, sans-serif;`, `font-family: 'RoboroSlab', sans-serif;`, etc. You may implement this across all your stylesheets. You may use this [article](https://speckyboy.com/good-bad-css-practices/) for more clarity.

2023-06-25 03:53 UTC, 1GORDON commented on src/styles/BookList.css
> +}
Great design @tomasesquivelgc 🤝

- [ ] As stated in the project requirements, we are supposed to replicate the given design as much as possible. Kindly ensure the highlighted section replicates the given design as much as possible. You may separate these elements properly.
- Your design
![your-design](https://github.com/tomasesquivelgc/React-Redux-bookstore/assets/63917725/1571ec83-1f2d-4523-b0ba-c72001f449e6)
- Given design
![Given design](https://github.com/tomasesquivelgc/React-Redux-bookstore/assets/63917725/edac34fd-e164-45f9-8cdf-51a010555fc1)

2023-08-26 20:19 UTC, ademibowale approved these changes
Hi @tomasesquivelgc , 


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- No linters errors ✔️
- Styling is EXACTLY the same as the one provided on [Zeplin](https://zeplin.io/)✔️
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good use of Github flow ✔️

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)




- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-26 21:06 UTC, merged